name: 'Auto Request Review'
description: 'Automatically requests review of a pull request based on files changes and/or groups the author belongs to 🤖'
branding:
  icon: 'at-sign'
  color: 'green'
inputs:
  token:
    required: true
  config:
    required: false
    default: '.github/owners.yml'
  use_local:
    required: false
    default: 'false'
  junit_report_path:
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
